# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      #run: mvn -B package --file pom.xml
      run: mvn clean install
    
    - name: move war file to parent directory
      run: mv /home/runner/work/hello-world/hello-world/webapp/target/webapp.war  /home/runner/work/hello-world/hello-world/

    - name: check directory
      run: ls /home/runner/work/hello-world/hello-world/

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: vichnik/docker-image
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        dockerfile: Dockerfile
    
    - name: check directory
      run: ls .